/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import controllers.ClientController;
import models.Klijent;
import models.Radnik;
import operations.Operation;
import operations.OperationType;
import tablemodels.KlijentTableModel;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author matij
 */
public class KlijentForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KlijentForm.class.getName());

    /**
     * Creates new form RadnikForm
     */
    private Radnik radnik;
    private KlijentTableModel tableModel;

    public KlijentForm(Radnik radnik) {
        this.radnik = radnik;
        initComponents();
        setTitle("Klijenti");
        tableModel = new KlijentTableModel();
        tblKlijenti.setModel(tableModel);
        tblKlijenti.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblKlijenti.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                popuniPoljaIzTabele();
            }
        });
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        btnDodaj.setText("Novi klijent");
        ucitajSve();
    }

    private void ucitajSve() {
        try {
            List<Klijent> lista = ClientController.getInstance().vratiSveKlijente();
            tableModel.setLista(lista);
        } catch (Exception e) {
            tableModel.setLista(new ArrayList<>());
            javax.swing.JOptionPane.showMessageDialog(this, "Greška pri učitavanju: " + e.getMessage());
        }
    }

    private void popuniPoljaIzTabele() {
        int row = tblKlijenti.getSelectedRow();
        if (row < 0) {
            return;
        }
        Klijent k = tableModel.getKlijentAt(row);
        try {
            Klijent found = (Klijent) ClientController.getInstance().sendOperation(
                new Operation(OperationType.PRETRAZI_KLIJENT, k.getIdKlijent())
            ).getResponse();
            txtAdresa.setText(found.getAdresa() != null ? found.getAdresa() : "");
            txtTelefon.setText(found.getTelefon() != null ? found.getTelefon() : "");
            txtEmail.setText(found.getEmail() != null ? found.getEmail() : "");
            javax.swing.JOptionPane.showMessageDialog(this, "Систем је нашао клијента");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Систем не може да нађе клијента");
        }
    }


    private void ocisti() {
        txtAdresa.setText("");
        txtTelefon.setText("");
        txtEmail.setText("");
        tblKlijenti.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTelefon = new javax.swing.JTextField();
        txtAdresa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlijenti = new javax.swing.JTable();
        btnPretrazi = new javax.swing.JButton();
        btnPromeni = new javax.swing.JButton();
        btnOcisti = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAdresa.addActionListener(this::txtAdresaActionPerformed);

        jLabel1.setText("Adresa");

        jLabel2.setText("Telefon");

        btnDodaj.setText("Napravi novog");
        btnDodaj.addActionListener(this::btnDodajActionPerformed);

        jLabel6.setText("Email");

        tblKlijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKlijenti);

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(this::btnPretraziActionPerformed);

        btnPromeni.setText("Promeni");
        btnPromeni.addActionListener(this::btnPromeniActionPerformed);

        btnOcisti.setText("Očisti");
        btnOcisti.addActionListener(this::btnOcistiActionPerformed);

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(this::btnObrisiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPretrazi)
                            .addComponent(btnPromeni)))
                    .addComponent(btnObrisi)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDodaj)
                                .addGap(18, 18, 18)
                                .addComponent(btnOcisti, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnOcisti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPretrazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPromeni)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObrisi)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdresaActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        KlijentUpravljanjeForm forma = new KlijentUpravljanjeForm();
        forma.setVisible(true);
        forma.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (forma.isSacuvano()) {
                    ucitajSve();
                }
            }
        });
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiActionPerformed
        ocisti();
        ucitajSve();
    }//GEN-LAST:event_btnOcistiActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        try {
            Klijent kriterijum = new Klijent();
            kriterijum.setAdresa(txtAdresa.getText().trim());
            kriterijum.setTelefon(txtTelefon.getText().trim());
            kriterijum.setEmail(txtEmail.getText().trim());
            List<Klijent> lista = ClientController.getInstance().vratiKlijentePo(kriterijum);
            tableModel.setLista(lista);
            if (lista != null && !lista.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Систем је нашао клијенте по задатим критеријумима");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Систем не може да нађе клијенте по задатим критеријумима");
            }
        } catch (Exception e) {
            tableModel.setLista(new ArrayList<>());
            javax.swing.JOptionPane.showMessageDialog(this, "Систем не може да нађе клијенте по задатим критеријумима");
        }    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniActionPerformed
        int row = tblKlijenti.getSelectedRow();
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Odaberite klijenta iz tabele.");
            return;
        }
        Klijent k = tableModel.getKlijentAt(row);
        KlijentUpravljanjeForm forma = new KlijentUpravljanjeForm(k);
        forma.setVisible(true);
        forma.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (forma.isSacuvano()) {
                    ucitajSve();
                }
            }
        });    }//GEN-LAST:event_btnPromeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int row = tblKlijenti.getSelectedRow();
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Odaberite klijenta iz tabele.");
            return;
        }
        int potvrda = javax.swing.JOptionPane.showConfirmDialog(this, "Brisanje klijenta je nepovratno. Nastavi?", "Potvrda", javax.swing.JOptionPane.YES_NO_OPTION);
        if (potvrda != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }
        int id = tableModel.getKlijentAt(row).getIdKlijent();
        try {
            ClientController.getInstance().obrisiKlijenta(id);
            javax.swing.JOptionPane.showMessageDialog(this, "Систем је обрисао клијента.");
            ucitajSve();
            ocisti();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Систем не може да обрише клијента");
        }    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KlijentForm(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOcisti;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKlijenti;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
