/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import controllers.ClientController;
import models.Oprema;
import models.Radnik;
import tablemodels.OpremaTableModel;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author matij
 */
public class OpremaForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OpremaForm.class.getName());

    /**
     * Creates new form OpremaForm
     */
    private Radnik radnik;
    private OpremaTableModel tableModel;

    public OpremaForm(Radnik radnik) {
        this.radnik = radnik;
        initComponents();
        setTitle("Oprema");
        spKol.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        tableModel = new OpremaTableModel();
        tblOprema.setModel(tableModel);
        tblOprema.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblOprema.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) popuniPoljaIzTabele();
        });
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ucitajSve();
    }

    private void ucitajSve() {
        try {
            List<Oprema> lista = ClientController.getInstance().vratiSvuOpremu();
            tableModel.setLista(lista);
        } catch (Exception e) {
            tableModel.setLista(new ArrayList<>());
            javax.swing.JOptionPane.showMessageDialog(this, "Greška pri učitavanju: " + e.getMessage());
        }
    }

    private void popuniPoljaIzTabele() {
        int row = tblOprema.getSelectedRow();
        if (row < 0) return;
        Oprema o = tableModel.getOpremaAt(row);
        txtNaziv.setText(o.getNaziv());
        txtSerijskiBroj.setText(o.getSerijskiBroj());
        txtCena.setText(String.valueOf(o.getCenaPoDanu()));
        spKol.setValue(o.getKolicinaDostupna());
    }

    private Oprema kreirajIzPolja() {
        String naziv = txtNaziv.getText().trim();
        String serijskiBroj = txtSerijskiBroj.getText().trim();
        String cenaStr = txtCena.getText().trim();
        if (naziv.isEmpty() || serijskiBroj.isEmpty() || cenaStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Popunite polja: Naziv, Serijski broj, Cena.");
            return null;
        }
        double cena;
        try { cena = Double.parseDouble(cenaStr); } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cena mora biti broj.");
            return null;
        }
        if (cena <= 0) { javax.swing.JOptionPane.showMessageDialog(this, "Cena mora biti veća od 0."); return null; }
        int kolicina = (int) spKol.getValue();
        if (kolicina <= 0) { javax.swing.JOptionPane.showMessageDialog(this, "Kolicina mora biti pozitivan broj."); return null; }
        Oprema o = new Oprema();
        o.setNaziv(naziv);
        o.setSerijskiBroj(serijskiBroj);
        o.setOpis("");
        o.setCenaPoDanu(cena);
        o.setKolicinaDostupna(kolicina);
        return o;
    }

    private void ocisti() {
        txtNaziv.setText("");
        txtSerijskiBroj.setText("");
        txtCena.setText("");
        spKol.setValue(1);
        tblOprema.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNaziv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSerijskiBroj = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOprema = new javax.swing.JTable();
        btnPretrazi = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnPromeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnOcisti = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        spKol = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naziv");

        jLabel2.setText("Serijski broj");

        jLabel3.setText("Cena");

        tblOprema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOprema);

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(this::btnPretraziActionPerformed);

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(this::btnDodajActionPerformed);

        btnPromeni.setText("Promeni");
        btnPromeni.addActionListener(this::btnPromeniActionPerformed);

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(this::btnObrisiActionPerformed);

        btnOcisti.setText("Očisti");
        btnOcisti.addActionListener(this::btnOcistiActionPerformed);

        jLabel4.setText("Kolicina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPromeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSerijskiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addComponent(btnDodaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCena, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(btnOcisti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(spKol)
                    .addComponent(btnPretrazi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spKol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSerijskiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnOcisti)
                    .addComponent(btnPretrazi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPromeni)
                    .addComponent(btnObrisi))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        try {
            Oprema kriterijum = new Oprema();
            kriterijum.setNaziv(txtNaziv.getText().trim());
            kriterijum.setSerijskiBroj(txtSerijskiBroj.getText().trim());
            List<Oprema> lista = ClientController.getInstance().pretrazujOpremu(kriterijum);
            tableModel.setLista(lista);
        } catch (Exception e) {
            tableModel.setLista(new ArrayList<>());
            javax.swing.JOptionPane.showMessageDialog(this, "Greška: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiActionPerformed
        ocisti();
        ucitajSve();
    }//GEN-LAST:event_btnOcistiActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        Oprema o = kreirajIzPolja();
        if (o == null) return;
        try {
            ClientController.getInstance().kreirajOpremu(o);
            ucitajSve(); ocisti();
        } catch (Exception e) { javax.swing.JOptionPane.showMessageDialog(this, "Greška: " + e.getMessage()); }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int row = tblOprema.getSelectedRow();
        if (row < 0) { javax.swing.JOptionPane.showMessageDialog(this, "Odaberite opremu iz tabele."); return; }
        int potvrda = javax.swing.JOptionPane.showConfirmDialog(this, "Brisanje opreme je nepovratno. Nastavi?", "Potvrda", javax.swing.JOptionPane.YES_NO_OPTION);
        if (potvrda != javax.swing.JOptionPane.YES_OPTION) return;
        int id = tableModel.getOpremaAt(row).getIdOprema();
        try {
            ClientController.getInstance().obrisiOpremu(id);
            ucitajSve(); ocisti();
        } catch (Exception e) { javax.swing.JOptionPane.showMessageDialog(this, "Greška: " + e.getMessage()); }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniActionPerformed
        int row = tblOprema.getSelectedRow();
        if (row < 0) { javax.swing.JOptionPane.showMessageDialog(this, "Odaberite opremu iz tabele."); return; }
        Oprema o = kreirajIzPolja();
        if (o == null) return;
        o.setIdOprema(tableModel.getOpremaAt(row).getIdOprema());
        try {
            ClientController.getInstance().promeniOpremu(o);
            ucitajSve(); ocisti();
        } catch (Exception e) { javax.swing.JOptionPane.showMessageDialog(this, "Greška: " + e.getMessage()); }
    }//GEN-LAST:event_btnPromeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OpremaForm(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOcisti;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spKol;
    private javax.swing.JTable tblOprema;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtSerijskiBroj;
    // End of variables declaration//GEN-END:variables
}
