/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import controllers.ClientController;
import models.Radnik;
import tablemodels.RadnikTableModel;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author matij
 */
public class RadnikForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RadnikForm.class.getName());

    /**
     * Creates new form RadnikForm
     */
    private Radnik trenutniRadnik;
    private RadnikTableModel tableModel;

    public RadnikForm(Radnik radnik) {
        this.trenutniRadnik = radnik;
        initComponents();
        setTitle("Radnici");
        tableModel = new RadnikTableModel();
        tblRadnici.setModel(tableModel);
        tblRadnici.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblRadnici.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) popuniPoljaIzTabele();
        });
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ucitajSve();
    }

    private void ucitajSve() {
        try {
            List<Radnik> lista = ClientController.getInstance().vratiSveRadnike();
            tableModel.setLista(lista);
        } catch (Exception e) {
            tableModel.setLista(new ArrayList<>());
            javax.swing.JOptionPane.showMessageDialog(this, "Greška pri učitavanju: " + e.getMessage());
        }
    }

    private void popuniPoljaIzTabele() {
        int row = tblRadnici.getSelectedRow();
        if (row < 0) return;
        Radnik r = tableModel.getRadnikAt(row);
        txtIme.setText(r.getIme());
        txtPrezime.setText(r.getPrezime());
        txtKorisnickoIme.setText(r.getKorisnickoIme());
        txtSifra.setText("");
        txtEmail.setText(r.getEmail());
    }

    private Radnik kreirajIzPolja() {
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String korisnickoIme = txtKorisnickoIme.getText().trim();
        String sifra = new String(txtSifra.getPassword()).trim();
        String email = txtEmail.getText().trim();
        if (ime.isEmpty() || prezime.isEmpty() || korisnickoIme.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ime, prezime i korisničko ime su obavezni.");
            return null;
        }
        Radnik r = new Radnik();
        r.setIme(ime);
        r.setPrezime(prezime);
        r.setKorisnickoIme(korisnickoIme);
        r.setSifra(sifra.isEmpty() ? null : sifra);
        r.setEmail(email);
        return r;
    }

    private void ocisti() {
        txtIme.setText("");
        txtPrezime.setText("");
        txtKorisnickoIme.setText("");
        txtSifra.setText("");
        txtEmail.setText("");
        tblRadnici.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JPasswordField();
        btnDodaj = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRadnici = new javax.swing.JTable();
        btnPretrazi = new javax.swing.JButton();
        btnPromeni = new javax.swing.JButton();
        btnOcisti = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPrezime.addActionListener(this::txtPrezimeActionPerformed);

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        jLabel3.setText("Lozinka");

        jLabel4.setText("Korisničko ime");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(this::btnDodajActionPerformed);

        jLabel6.setText("Email");

        tblRadnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRadnici);

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(this::btnPretraziActionPerformed);

        btnPromeni.setText("Promeni");
        btnPromeni.addActionListener(this::btnPromeniActionPerformed);

        btnOcisti.setText("Očisti");
        btnOcisti.addActionListener(this::btnOcistiActionPerformed);

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(this::btnObrisiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPretrazi)
                            .addComponent(btnPromeni)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrezime))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDodaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnOcisti, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEmail)))
                    .addComponent(btnObrisi))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDodaj)
                            .addComponent(btnOcisti))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPretrazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPromeni)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObrisi)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrezimeActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        Radnik r = kreirajIzPolja();
        if (r == null) return;
        if (new String(txtSifra.getPassword()).trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Šifra je obavezna pri dodavanju.");
            return;
        }
        try {
            ClientController.getInstance().kreirajRadnika(r);
            ucitajSve(); ocisti();
        } catch (Exception e) { javax.swing.JOptionPane.showMessageDialog(this, "Greška: " + e.getMessage()); }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiActionPerformed
        ocisti();
        ucitajSve();
    }//GEN-LAST:event_btnOcistiActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        try {
            Radnik kriterijum = new Radnik();
            kriterijum.setIme(txtIme.getText().trim());
            kriterijum.setPrezime(txtPrezime.getText().trim());
            kriterijum.setKorisnickoIme(txtKorisnickoIme.getText().trim());
            kriterijum.setEmail(txtEmail.getText().trim());
            List<Radnik> lista = ClientController.getInstance().pretrazujRadnike(kriterijum);
            tableModel.setLista(lista);
        } catch (Exception e) {
            tableModel.setLista(new ArrayList<>());
            javax.swing.JOptionPane.showMessageDialog(this, "Greška: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniActionPerformed
        int row = tblRadnici.getSelectedRow();
        if (row < 0) { javax.swing.JOptionPane.showMessageDialog(this, "Odaberite radnika iz tabele."); return; }
        Radnik r = kreirajIzPolja();
        if (r == null) return;
        r.setIdRadnik(tableModel.getRadnikAt(row).getIdRadnik());
        try {
            ClientController.getInstance().promeniRadnika(r);
            ucitajSve(); ocisti();
        } catch (Exception e) { javax.swing.JOptionPane.showMessageDialog(this, "Greška: " + e.getMessage()); }
    }//GEN-LAST:event_btnPromeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int row = tblRadnici.getSelectedRow();
        if (row < 0) { javax.swing.JOptionPane.showMessageDialog(this, "Odaberite radnika iz tabele."); return; }
        int potvrda = javax.swing.JOptionPane.showConfirmDialog(this, "Brisanje radnika je nepovratno. Nastavi?", "Potvrda", javax.swing.JOptionPane.YES_NO_OPTION);
        if (potvrda != javax.swing.JOptionPane.YES_OPTION) return;
        int id = tableModel.getRadnikAt(row).getIdRadnik();
        try {
            ClientController.getInstance().obrisiRadnika(id);
            ucitajSve(); ocisti();
        } catch (Exception e) { javax.swing.JOptionPane.showMessageDialog(this, "Greška: " + e.getMessage()); }
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RadnikForm(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOcisti;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRadnici;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JPasswordField txtSifra;
    // End of variables declaration//GEN-END:variables
}
