/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import controllers.ClientController;
import models.Radnik;
import models.StrucnaSprema;
import tablemodels.StrucnaSpremaTableModel;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author matij
 */
public class StrucnaSpremaForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StrucnaSpremaForm.class.getName());

    /**
     * Creates new form StrucnaSpremaForm
     */
    private Radnik radnik;
    private StrucnaSpremaTableModel tableModel;

    public StrucnaSpremaForm(Radnik radnik) {
        this.radnik = radnik;
        initComponents();
        setTitle("Stručna sprema");
        cmbStepen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "", "I stepen", "II stepen", "III stepen", "IV stepen", "V stepen", "VI stepen", "VII stepen"
        }));
        tableModel = new StrucnaSpremaTableModel();
        tblSprema.setModel(tableModel);
        tblSprema.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblSprema.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) popuniPoljaIzTabele();
        });
        btnObrisi.setEnabled(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ucitajSve();
    }

    private void ucitajSve() {
        try {
            List<StrucnaSprema> lista = ClientController.getInstance().vratiSveStrucneSpreme();
            tableModel.setLista(lista);
        } catch (Exception e) {
            tableModel.setLista(new ArrayList<>());
            javax.swing.JOptionPane.showMessageDialog(this, "Greška pri učitavanju: " + e.getMessage());
        }
    }

    private void popuniPoljaIzTabele() {
        int row = tblSprema.getSelectedRow();
        if (row < 0) return;
        StrucnaSprema ss = tableModel.getStrucnaSpremaAt(row);
        txtNaziv.setText(ss.getNazivSpreme());
        cmbStepen.setSelectedItem(ss.getStepen());
    }

    private void ocisti() {
        txtNaziv.setText("");
        cmbStepen.setSelectedIndex(0);
        tblSprema.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        cmbStepen = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSprema = new javax.swing.JTable();
        btnPretrazi = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnOcisti = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naziv spreme");

        jLabel2.setText("Stepen");

        tblSprema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSprema);

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(this::btnPretraziActionPerformed);

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(this::btnDodajActionPerformed);

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(this::btnObrisiActionPerformed);

        btnOcisti.setText("Očisti");
        btnOcisti.addActionListener(this::btnOcistiActionPerformed);

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(this::btnIzmeniActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbStepen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOcisti)
                            .addComponent(btnPretrazi)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisi)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOcisti)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbStepen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi)
                    .addComponent(btnIzmeni))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        int selectedRow = tblSprema.getSelectedRow();
        if (selectedRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Odaberite stavku iz tabele za izmenu.");
            return;
        }
        String naziv = txtNaziv.getText().trim();
        String stepen = (String) cmbStepen.getSelectedItem();
        if (naziv.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Unesite naziv stručne spreme.");
            return;
        }
        try {
            StrucnaSprema ss = new StrucnaSprema();
            ss.setIdStrucnaSprema(tableModel.getStrucnaSpremaAt(selectedRow).getIdStrucnaSprema());
            ss.setNazivSpreme(naziv);
            ss.setStepen(stepen);
            ClientController.getInstance().promeniStrucnuSpremu(ss);
            ucitajSve(); ocisti();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Greška: " + e.getMessage());
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int selectedRow = tblSprema.getSelectedRow();
        if (selectedRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Odaberite stavku iz tabele za brisanje.");
            return;
        }
        int conf = javax.swing.JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite obrisati odabranu stavku?", "Potvrda brisanja", javax.swing.JOptionPane.YES_NO_OPTION);
        if (conf != javax.swing.JOptionPane.YES_OPTION) return;
        try {
            StrucnaSprema ss = tableModel.getStrucnaSpremaAt(selectedRow);
            ClientController.getInstance().obrisiStrucnuSpremu(ss);
            ucitajSve(); ocisti();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Greška: " + e.getMessage());
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        String naziv = txtNaziv.getText().trim();
        String stepen = (String) cmbStepen.getSelectedItem();
        if (naziv.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Unesite naziv stručne spreme.");
            return;
        }
        try {
            StrucnaSprema ss = new StrucnaSprema();
            ss.setNazivSpreme(naziv);
            ss.setStepen(stepen);
            ClientController.getInstance().kreirajStrucnuSpremu(ss);
            javax.swing.JOptionPane.showMessageDialog(this, "Систем је запамтио струčну спрему.");
            ucitajSve();
            ocisti();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Систем не може да запамти стручну спрему");
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiActionPerformed
        ocisti();
        ucitajSve();
    }//GEN-LAST:event_btnOcistiActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        try {
            StrucnaSprema kriterijum = new StrucnaSprema();
            kriterijum.setNazivSpreme(txtNaziv.getText().trim());
            String stepen = (String) cmbStepen.getSelectedItem();
            kriterijum.setStepen(stepen != null && !stepen.isEmpty() ? stepen : null);
            List<StrucnaSprema> lista = ClientController.getInstance().pretrazujStrucneSpreme(kriterijum);
            tableModel.setLista(lista);
        } catch (Exception e) {
            tableModel.setLista(new ArrayList<>());
            javax.swing.JOptionPane.showMessageDialog(this, "Greška: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StrucnaSpremaForm(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOcisti;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JComboBox<String> cmbStepen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSprema;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables
}
