package operations;

public enum OperationType {

    // --- Autentifikacija ---
    PRIJAVI_RADNIK,

    // --- Ugovor ---
    KREIRAJ_UGOVOR,
    PRETRAZI_UGOVOR,
    PROMENI_UGOVOR,
    PROVERI_DOSTUPNOST_OPREME,
    VRATI_LISTU_UGOVOR_PO_UGOVORU,
    VRATI_LISTU_UGOVOR_PO_RADNIKU,
    VRATI_LISTU_UGOVOR_PO_KLIJENTU,
    VRATI_LISTU_UGOVOR_PO_OPREMI,

    // --- Klijent ---
    KREIRAJ_KLIJENT,
    PRETRAZI_KLIJENT,
    PROMENI_KLIJENT,
    OBRISI_KLIJENT,
    VRATI_LISTU_KLIJENT,
    VRATI_LISTU_SVI_KLIJENT,

    // --- PravnoLice ---
    KREIRAJ_PRAVNO_LICE,
    UBACI_PRAVNO_LICE,
    PRETRAZI_PRAVNO_LICE,
    PROMENI_PRAVNO_LICE,
    OBRISI_PRAVNO_LICE,
    VRATI_LISTU_PRAVNO_LICE_PO_PRAVNOM_LICU,
    VRATI_LISTU_PRAVNO_LICE_PO_KLIJENTU,

    // --- FizickoLice ---
    KREIRAJ_FIZICKO_LICE,
    UBACI_FIZICKO_LICE,
    PRETRAZI_FIZICKO_LICE,
    PROMENI_FIZICKO_LICE,
    OBRISI_FIZICKO_LICE,
    VRATI_LISTU_FIZICKO_LICE_PO_FIZICKOM_LICU,
    VRATI_LISTU_FIZICKO_LICE_PO_KLIJENTU,

    // --- Radnik ---
    KREIRAJ_RADNIK,
    PRETRAZI_RADNIK,
    PROMENI_RADNIK,
    OBRISI_RADNIK,
    VRATI_LISTU_SVI_RADNIK,
    VRATI_LISTU_RADNIK_PO_RADNIKU,
    VRATI_LISTU_RADNIK_PO_STRUCNOJ_SPREMI,

    // --- Oprema ---
    KREIRAJ_OPREMA,
    PRETRAZI_OPREMA,
    PROMENI_OPREMA,
    OBRISI_OPREMA,
    VRATI_LISTU_OPREMA,
    VRATI_LISTU_SVI_OPREMA,

    // --- StrucnaSprema ---
    KREIRAJ_STRUCNA_SPREMA,
    UBACI_STRUCNA_SPREMA,
    PRETRAZI_STRUCNA_SPREMA,
    PROMENI_STRUCNA_SPREMA,
    VRATI_LISTU_STRUCNA_SPREMA,
    VRATI_LISTU_SVI_STRUCNA_SPREMA,
    OBRISI_STRUCNA_SPREMA
}
